name: unifi
version: 0.1.3
description: >-
  A Dart implementation that provides access to Unifi Controllers API 6.x and later.
homepage: https://github.com/kacao/dart-unifi
environment:
  sdk: '>=2.13.0 <3.0.0'
dependencies: 
  http: ^0.13.1
  build_runner: ^2.0.0
  build_verify: ^2.0.0
  json_serializable: ^5.0.0
  logging: ^1.0.1
  path: ^1.8.0
  test: ^1.16.8
dev_dependencies: 
  dotenv: ^3.0.0-nullsafety.0
