name: unifi
version: 0.1.0
description: >-
  A Dart implementation that provides access to Unifi Controllers API 6.x and later.
homepage: https://github.com/kacao/dart-unifi
environment:
  sdk: '>=2.10.0 <3.0.0'
dependencies: 
  http: ^0.13.1
  logging: ^1.0.1
  path: ^1.8.0
  test: ^1.16.8
dev_dependencies: 
  dotenv: ^3.0.0-nullsafety.0
